In [1]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path("../data")

In [3]:
fighters_primary = pd.read_csv(DATA_DIR / "fighter_details.csv")
fighters_secondary = pd.read_csv(DATA_DIR / "ufc-fighters-statistics.csv")
fights = pd.read_csv(DATA_DIR / "fight_details.csv")
events = pd.read_csv(DATA_DIR / "event_details.csv")
ufc = pd.read_csv(DATA_DIR / "UFC.csv")

In [4]:
print("fighters_primary:", fighters_primary.shape)
print("fighters_secondary:", fighters_secondary.shape)
print("fights:", fights.shape)
print("events:", events.shape)
print("ufc:", ufc.shape)

fighters_primary: (2611, 19)
fighters_secondary: (4111, 18)
fights: (8337, 86)
events: (8337, 6)
ufc: (8337, 124)

In [5]:
for name, df in {
    "fighters_primary": fighters_primary,
    "fighters_secondary": fighters_secondary,
    "fights": fights,
    "events": events,
    "ufc": ufc,
}.items():
    print(f"\n{name.upper()}")
    print(df.columns.tolist())

FIGHTERS_PRIMARY
['id', 'name', 'nick_name', 'wins', 'losses', 'draws', 'height', 'weight', 'reach', 'stance', 'dob', 'splm', 'str_acc', 'sapm', 'str_def', 'td_avg', 'td_avg_acc', 'td_def', 'sub_avg']

FIGHTERS_SECONDARY
['name', 'nickname', 'wins', 'losses', 'draws', 'height_cm', 'weight_in_kg', 'reach_in_cm', 'stance', 'date_of_birth', 'significant_strikes_landed_per_minute', 'significant_striking_accuracy', 'significant_strikes_absorbed_per_minute', 'significant_strike_defence', 'average_takedowns_landed_per_15_minutes', 'takedown_accuracy', 'takedown_defense', 'average_submissions_attempted_per_15_minutes']

FIGHTS
['event_name', 'event_id', 'fight_id', 'r_name', 'r_id', 'b_name', 'b_id', 'division', 'title_fight', 'method', 'finish_round', 'match_time_sec', 'total_rounds', 'referee', 'r_kd', 'r_sig_str_landed', 'r_sig_str_atmpted', 'r_sig_str_acc', 'r_total_str_landed', 'r_total_str_atmpted', 'r_total_str_acc', 'r_td_landed', 'r_td_atmpted', 'r_td_acc', 'r_sub_att', 'r_ctrl', 'r_head_landed', 'r_head_atmpted', 'r_head_acc', 'r_body_landed', 'r_body_atmpted', 'r_body_acc', 'r_leg_landed', 'r_leg_atmpted', 'r_leg_acc', 'r_dist_landed', 'r_dist_atmpted', 'r_dist_acc', 'r_clinch_landed', 'r_clinch_atmpted', 'r_clinch_acc', 'r_ground_landed', 'r_ground_atmpted', 'r_ground_acc', 'r_landed_head_per', 'r_landed_body_per', 'r_landed_leg_per', 'r_landed_dist_per', 'r_landed_clinch_per', 'r_landed_ground_per', 'b_kd', 'b_sig_str_landed', 'b_sig_str_atmpted', 'b_sig_str_acc', 'b_total_str_landed', 'b_total_str_atmpted', 'b_total_str_acc', 'b_td_landed', 'b_td_atmpted', 'b_td_acc', 'b_sub_att', 'b_ctrl', 'b_head_landed', 'b_head_atmpted', 'b_head_acc', 'b_body_landed', 'b_body_atmpted', 'b_body_acc', 'b_leg_landed', 'b_leg_atmpted', 'b_leg_acc', 'b_dist_landed', 'b_dist_atmpted', 'b_dist_acc', 'b_clinch_landed', 'b_clinch_atmpted', 'b_clinch_acc', 'b_ground_landed', 'b_ground_atmpted', 'b_ground_acc', 'b_landed_head_per', 'b_landed_body_per', 'b_landed_leg_per', 'b_landed_dist_per', 'b_landed_clinch_per', 'b_landed_ground_per']

EVENTS
['event_id', 'fight_id', 'date', 'location', 'winner', 'winner_id']

UFC
['event_id', 'event_name', 'date', 'location', 'fight_id', 'division', 'title_fight', 'method', 'finish_round', 'match_time_sec', 'total_rounds', 'referee', 'r_name', 'r_id', 'r_kd', 'r_sig_str_landed', 'r_sig_str_atmpted', 'r_sig_str_acc', 'r_total_str_landed', 'r_total_str_atmpted', 'r_total_str_acc', 'r_td_landed', 'r_td_atmpted', 'r_td_acc', 'r_sub_att', 'r_ctrl', 'r_head_landed', 'r_head_atmpted', 'r_head_acc', 'r_body_landed', 'r_body_atmpted', 'r_body_acc', 'r_leg_landed', 'r_leg_atmpted', 'r_leg_acc', 'r_dist_landed', 'r_dist_atmpted', 'r_dist_acc', 'r_clinch_landed', 'r_clinch_atmpted', 'r_clinch_acc', 'r_ground_landed', 'r_ground_atmpted', 'r_ground_acc', 'r_landed_head_per', 'r_landed_body_per', 'r_landed_leg_per', 'r_landed_dist_per', 'r_landed_clinch_per', 'r_landed_ground_per', 'r_nick_name', 'r_wins', 'r_losses', 'r_draws', 'r_height', 'r_weight', 'r_reach', 'r_stance', 'r_dob', 'r_splm', 'r_str_acc', 'r_sapm', 'r_str_def', 'r_td_avg', 'r_td_avg_acc', 'r_td_def', 'r_sub_avg', 'b_name', 'b_id', 'b_kd', 'b_sig_str_landed', 'b_sig_str_atmpted', 'b_sig_str_acc', 'b_total_str_landed', 'b_total_str_atmpted', 'b_total_str_acc', 'b_td_landed', 'b_td_atmpted', 'b_td_acc', 'b_sub_att', 'b_ctrl', 'b_head_landed', 'b_head_atmpted', 'b_head_acc', 'b_body_landed', 'b_body_atmpted', 'b_body_acc', 'b_leg_landed', 'b_leg_atmpted', 'b_leg_acc', 'b_dist_landed', 'b_dist_atmpted', 'b_dist_acc', 'b_clinch_landed', 'b_clinch_atmpted', 'b_clinch_acc', 'b_ground_landed', 'b_ground_atmpted', 'b_ground_acc', 'b_landed_head_per', 'b_landed_body_per', 'b_landed_leg_per', 'b_landed_dist_per', 'b_landed_clinch_per', 'b_landed_ground_per', 'b_nick_name', 'b_wins', 'b_losses', 'b_draws', 'b_height', 'b_weight', 'b_reach', 'b_stance', 'b_dob', 'b_splm', 'b_str_acc', 'b_sapm', 'b_str_def', 'b_td_avg', 'b_td_avg_acc', 'b_td_def', 'b_sub_avg', 'winner', 'winner_id']

In [6]:
ufc.columns.tolist()

['event_id',
 'event_name',
 'date',
 'location',
 'fight_id',
 'division',
 'title_fight',
 'method',
 'finish_round',
 'match_time_sec',
 'total_rounds',
 'referee',
 'r_name',
 'r_id',
 'r_kd',
 'r_sig_str_landed',
 'r_sig_str_atmpted',
 'r_sig_str_acc',
 'r_total_str_landed',
 'r_total_str_atmpted',
 'r_total_str_acc',
 'r_td_landed',
 'r_td_atmpted',
 'r_td_acc',
 'r_sub_att',
 'r_ctrl',
 'r_head_landed',
 'r_head_atmpted',
 'r_head_acc',
 'r_body_landed',
 'r_body_atmpted',
 'r_body_acc',
 'r_leg_landed',
 'r_leg_atmpted',
 'r_leg_acc',
 'r_dist_landed',
 'r_dist_atmpted',
 'r_dist_acc',
 'r_clinch_landed',
 'r_clinch_atmpted',
 'r_clinch_acc',
 'r_ground_landed',
 'r_ground_atmpted',
 'r_ground_acc',
 'r_landed_head_per',
 'r_landed_body_per',
 'r_landed_leg_per',
 'r_landed_dist_per',
 'r_landed_clinch_per',
 'r_landed_ground_per',
 'r_nick_name',
 'r_wins',
 'r_losses',
 'r_draws',
 'r_height',
 'r_weight',
 'r_reach',
 'r_stance',
 'r_dob',
 'r_splm',
 'r_str_acc',
 'r_sapm',
 'r_str_def',
 'r_td_avg',
 'r_td_avg_acc',
 'r_td_def',
 'r_sub_avg',
 'b_name',
 'b_id',
 'b_kd',
 'b_sig_str_landed',
 'b_sig_str_atmpted',
 'b_sig_str_acc',
 'b_total_str_landed',
 'b_total_str_atmpted',
 'b_total_str_acc',
 'b_td_landed',
 'b_td_atmpted',
 'b_td_acc',
 'b_sub_att',
 'b_ctrl',
 'b_head_landed',
 'b_head_atmpted',
 'b_head_acc',
 'b_body_landed',
 'b_body_atmpted',
 'b_body_acc',
 'b_leg_landed',
 'b_leg_atmpted',
 'b_leg_acc',
 'b_dist_landed',
 'b_dist_atmpted',
 'b_dist_acc',
 'b_clinch_landed',
 'b_clinch_atmpted',
 'b_clinch_acc',
 'b_ground_landed',
 'b_ground_atmpted',
 'b_ground_acc',
 'b_landed_head_per',
 'b_landed_body_per',
 'b_landed_leg_per',
 'b_landed_dist_per',
 'b_landed_clinch_per',
 'b_landed_ground_per',
 'b_nick_name',
 'b_wins',
 'b_losses',
 'b_draws',
 'b_height',
 'b_weight',
 'b_reach',
 'b_stance',
 'b_dob',
 'b_splm',
 'b_str_acc',
 'b_sapm',
 'b_str_def',
 'b_td_avg',
 'b_td_avg_acc',
 'b_td_def',
 'b_sub_avg',
 'winner',
 'winner_id']

In [7]:
ufc.head(3)

,event_id,event_name,date,location,fight_id,division,title_fight,method,finish_round,match_time_sec,...,b_splm,b_str_acc,b_sapm,b_str_def,b_td_avg,b_td_avg_acc,b_td_def,b_sub_avg,winner,winner_id
0,6e380a4d73ab4f0e,UFC Fight Night: Imavov vs. Borralho,2025/09/06,"Paris, Ile-de-France, France",d14fea43712707f0,lightweight,0,Submission,2,176,...,3.84,57,4.16,60,0.00,0,84,0.0,Benoit Saint Denis,c2299ec916bc7c56
1,6e380a4d73ab4f0e,UFC Fight Night: Imavov vs. Borralho,2025/09/06,"Paris, Ile-de-France, France",5bcd8abf6da01dae,middleweight,0,Decision - Unanimous,5,300,...,3.44,56,2.50,60,1.28,48,76,0.4,Nassourdine Imavov,881bf86d4cba8578
2,6e380a4d73ab4f0e,UFC Fight Night: Imavov vs. Borralho,2025/09/06,"Paris, Ile-de-France, France",0149e875b31e57f8,light heavyweight,0,KO/TKO,1,300,...,2.50,45,3.04,43,1.43,18,35,1.3,Modestas Bukauskas,476fe566d2df676e

In [8]:
audit = pd.DataFrame({
    "dtype": ufc.dtypes.astype(str),
    "missing_count": ufc.isna().sum(),
    "missing_percent": (ufc.isna().mean() * 100).round(2),
    "unique_values": ufc.nunique()
}).sort_values("missing_percent", ascending=False)

audit.head(30)

                   dtype  missing_count  missing_percent  unique_values
b_ground_acc     float64           3816            45.77             83
b_td_acc         float64           3126            37.50             72
r_ground_acc     float64           2956            35.46             83
r_td_acc         float64           2686            32.22             74
b_nick_name          str           2388            28.64           1325
r_nick_name          str           2328            27.92           1103
b_clinch_acc     float64           2042            24.49             82
r_clinch_acc     float64           2003            24.03             80
r_leg_acc        float64           1584            19.00             72
b_leg_acc        float64           1568            18.81             75
b_body_acc       float64            997            11.96             87
b_reach          float64            901            10.81             27
r_body_acc       float64            858            10.29             83
r_reach          float64            420             5.04             27
b_ctrl           float64            202             2.42            668
r_ctrl           float64            202             2.42            785
b_dob                str            182             2.18           2038
b_head_acc       float64            157             1.88             90
winner_id            str            147             1.76           1829
winner               str            147             1.76           1828
r_dist_acc       float64            139             1.67             89
b_dist_acc       float64            129             1.55             83
r_head_acc       float64             99             1.19             95
b_sig_str_acc    float64             79             0.95             91
b_stance             str             70             0.84              5
r_dob                str             69             0.83           1679
r_sig_str_acc    float64             59             0.71             96
b_total_str_acc  float64             57             0.68             95
r_total_str_acc  float64             48             0.58             93
total_rounds     float64             31             0.37              4

In [9]:
ufc["winner"].value_counts(dropna=False)

winner
NaN                 147
Jim Miller           27
Neil Magny           23
Max Holloway         23
Charles Oliveira     23
                   ...
Marcus Bossett        1
Jason DeLucia         1
Orlando Wiet          1
Frank Hamaker         1
Scott Morris          1
Name: count, Length: 1829, dtype: int64

In [10]:
ufc["winner"].head(20).tolist()

['Benoit Saint Denis',
 'Nassourdine Imavov',
 'Modestas Bukauskas',
 'Mason Jones',
 'Axel Sola',
 'Oumar Sy',
 'William Gomis',
 'Ante Delija',
 'Kaue Fernandes',
 'Rinat Fakhretdinov',
 'Sam Patterson',
 'Robert Bryczek',
 'Johnny Walker',
 'Sam Hughes',
 'Aljamain Sterling',
 'Sergei Pavlovich',
 'Sumudaerji',
 'Taiyilake Nueraji',
 'Gauge Young',
 'Rongzhu']

In [11]:
ufc[["winner", "r_name", "b_name"]].head(10)

               winner              r_name              b_name
0  Benoit Saint Denis  Benoit Saint Denis      Mauricio Ruffy
1  Nassourdine Imavov  Nassourdine Imavov       Caio Borralho
2  Modestas Bukauskas  Modestas Bukauskas          Paul Craig
3         Mason Jones          Bolaji Oki         Mason Jones
4           Axel Sola           Axel Sola          Rhys McKee
5            Oumar Sy            Oumar Sy    Brendson Ribeiro
6       William Gomis       William Gomis      Robert Ruchala
7         Ante Delija       Marcin Tybura         Ante Delija
8      Kaue Fernandes      Harry Hardwick      Kaue Fernandes
9  Rinat Fakhretdinov  Andreas Gustafsson  Rinat Fakhretdinov

In [12]:
ufc = ufc.dropna(subset=["winner"]).copy()

ufc["target"] = (ufc["winner"] == ufc["r_name"]).astype(int)

ufc["target"].value_counts()

target
1    5291
0    2899
Name: count, dtype: int64

In [13]:
ufc["target"].value_counts(normalize=True) * 100

target
1    64.603175
0    35.396825
Name: proportion, dtype: float64

In [14]:
features = [
    "r_wins",
    "r_losses",
    "r_height",
    "r_weight",
    "r_reach",
    "r_splm",
    "r_str_acc",
    "r_sapm",
    "r_str_def",
    "r_td_avg",
    "r_td_avg_acc",
    "r_td_def",
    "r_sub_avg",

    "b_wins",
    "b_losses",
    "b_height",
    "b_weight",
    "b_reach",
    "b_splm",
    "b_str_acc",
    "b_sapm",
    "b_str_def",
    "b_td_avg",
    "b_td_avg_acc",
    "b_td_def",
    "b_sub_avg",

    "division",
    "title_fight"
]

ml_df = ufc[features + ["target"]].copy()

ml_df.shape

(8190, 29)

In [15]:
ml_df.isna().sum().sort_values(ascending=False)

b_reach         886
r_reach         411
b_height         21
b_weight         19
r_height          5
r_weight          3
b_str_def         0
b_splm            0
b_str_acc         0
b_sapm            0
r_wins            0
b_td_avg          0
b_td_avg_acc      0
b_sub_avg         0
division          0
title_fight       0
b_td_def          0
b_losses          0
r_losses          0
b_wins            0
r_sub_avg         0
r_td_def          0
r_td_avg_acc      0
r_td_avg          0
r_str_def         0
r_sapm            0
r_str_acc         0
r_splm            0
target            0
dtype: int64

In [16]:
ml_df.dtypes

r_wins            int64
r_losses          int64
r_height        float64
r_weight        float64
r_reach         float64
r_splm          float64
r_str_acc         int64
r_sapm          float64
r_str_def         int64
r_td_avg        float64
r_td_avg_acc      int64
r_td_def          int64
r_sub_avg       float64
b_wins            int64
b_losses          int64
b_height        float64
b_weight        float64
b_reach         float64
b_splm          float64
b_str_acc         int64
b_sapm          float64
b_str_def         int64
b_td_avg        float64
b_td_avg_acc      int64
b_td_def          int64
b_sub_avg       float64
division            str
title_fight       int64
target            int64
dtype: object

In [17]:
df = ml_df.copy()

# Reach / size
df["height_diff"] = df["r_height"] - df["b_height"]
df["weight_diff"] = df["r_weight"] - df["b_weight"]
df["reach_diff"] = df["r_reach"] - df["b_reach"]

# Experience
df["wins_diff"] = df["r_wins"] - df["b_wins"]
df["losses_diff"] = df["r_losses"] - df["b_losses"]

# Striking
df["splm_diff"] = df["r_splm"] - df["b_splm"]
df["str_acc_diff"] = df["r_str_acc"] - df["b_str_acc"]
df["sapm_diff"] = df["r_sapm"] - df["b_sapm"]
df["str_def_diff"] = df["r_str_def"] - df["b_str_def"]

# Wrestling
df["td_avg_diff"] = df["r_td_avg"] - df["b_td_avg"]
df["td_acc_diff"] = df["r_td_avg_acc"] - df["b_td_avg_acc"]
df["td_def_diff"] = df["r_td_def"] - df["b_td_def"]

# Submission threat
df["sub_avg_diff"] = df["r_sub_avg"] - df["b_sub_avg"]

df.head()

,r_wins,r_losses,r_height,r_weight,r_reach,r_splm,r_str_acc,r_sapm,r_str_def,r_td_avg,...,wins_diff,losses_diff,splm_diff,str_acc_diff,sapm_diff,str_def_diff,td_avg_diff,td_acc_diff,td_def_diff,sub_avg_diff
0,15,3,180.34,70.31,185.42,5.05,55,4.19,42,4.35,...,3,1,1.21,-2,0.03,-18,4.35,37,-14,1.6
1,17,4,190.50,83.91,190.50,4.28,54,3.17,58,0.74,...,0,2,0.84,-2,0.67,-2,-0.54,-16,5,0.6
2,19,6,190.50,92.99,193.04,3.32,43,3.93,51,0.30,...,2,-4,0.82,-2,0.89,8,-1.13,48,45,-1.2
3,10,3,177.80,70.31,185.42,6.59,44,5.15,61,1.01,...,-7,1,0.88,3,0.68,11,-3.16,5,-15,-0.2
4,11,0,187.96,77.11,187.96,3.74,42,2.74,75,1.25,...,-3,-7,-0.97,2,-4.41,28,1.25,25,-47,0.0

In [18]:
df["division"].value_counts()

division
lightweight      1366
welterweight     1322
middleweight     1067
featherweight     791
heavyweight       710
                 ...
6 tournament        1
5 tournament        1
3 tournament        1
4 tournament        1
2 tournament        1
Name: count, Length: 107, dtype: int64

In [19]:
sorted(df["division"].unique())

['10 tournament',
 '13 heavyweight tournament',
 '13 lightweight tournament',
 '14 heavyweight tournament',
 '14 middleweight tournament',
 '15 heavyweight tournament',
 '17 middleweight tournament',
 '2 tournament',
 '3 tournament',
 '4 tournament',
 '5 tournament',
 '6 tournament',
 '7 tournament',
 '8 tournament',
 'bantamweight',
 'catch weight',
 'featherweight',
 'flyweight',
 'heavyweight',
 'interim bantamweight',
 'interim featherweight',
 'interim flyweight',
 'interim heavyweight',
 'interim light heavyweight',
 'interim lightweight',
 'interim middleweight',
 'interim welterweight',
 'light heavyweight',
 'lightweight',
 'middleweight',
 'open weight',
 'road to  1 bantamweight tournament',
 'road to  1 featherweight tournament',
 'road to  1 flyweight tournament',
 'road to  1 lightweight tournament',
 'road to  3 bantamweight tournament',
 'road to  3 flyweight tournament',
 "road to  3 women's strawweight tournament",
 'super heavyweight',
 'superfight championship',
 'tuf nations canada vs. australia middleweight tournament',
 'tuf nations canada vs. australia welterweight tournament',
 'ultimate fighter 1 light heavyweight tournament',
 'ultimate fighter 1 middleweight tournament',
 'ultimate fighter 10 heavyweight tournament',
 'ultimate fighter 11 middleweight tournament',
 'ultimate fighter 12 lightweight tournament',
 'ultimate fighter 13 welterweight tournament',
 'ultimate fighter 14 bantamweight tournament',
 'ultimate fighter 14 featherweight tournament',
 'ultimate fighter 15 lightweight tournament',
 'ultimate fighter 16 welterweight tournament',
 'ultimate fighter 17 middleweight tournament',
 'ultimate fighter 18 bantamweight tournament',
 "ultimate fighter 18 women's bantamweight tournament",
 'ultimate fighter 19 light heavyweight tournament',
 'ultimate fighter 19 middleweight tournament',
 'ultimate fighter 2 heavyweight tournament',
 'ultimate fighter 2 welterweight tournament',
 'ultimate fighter 21 welterweight tournament',
 'ultimate fighter 22 lightweight tournament',
 'ultimate fighter 23 light heavyweight tournament',
 "ultimate fighter 23 women's strawweight tournament",
 'ultimate fighter 25 welterweight tournament',
 'ultimate fighter 27 featherweight tournament',
 'ultimate fighter 27 lightweight tournament',
 'ultimate fighter 28 heavyweight tournament',
 "ultimate fighter 28 women's featherweight tournament",
 'ultimate fighter 3 light heavyweight tournament',
 'ultimate fighter 3 middleweight tournament',
 'ultimate fighter 32 featherweight tournament',
 'ultimate fighter 32 middleweight tournament',
 'ultimate fighter 33 flyweight tournament',
 'ultimate fighter 4 middleweight tournament',
 'ultimate fighter 4 welterweight tournament',
 'ultimate fighter 5 lightweight tournament',
 'ultimate fighter 6 welterweight tournament',
 'ultimate fighter 7 middleweight tournament',
 'ultimate fighter 8 light heavyweight tournament',
 'ultimate fighter 8 lightweight tournament',
 'ultimate fighter 9 lightweight tournament',
 'ultimate fighter 9 welterweight tournament',
 'ultimate fighter australia vs. uk lightweight tournament',
 'ultimate fighter australia vs. uk welterweight tournament',
 'ultimate fighter brazil 1 featherweight tournament',
 'ultimate fighter brazil 1 middleweight tournament',
 'ultimate fighter brazil 2 welterweight tournament',
 'ultimate fighter brazil 3 heavyweight tournament',
 'ultimate fighter brazil 3 middleweight tournament',
 'ultimate fighter brazil 4 bantamweight tournament',
 'ultimate fighter brazil 4 lightweight tournament',
 'ultimate fighter china featherweight tournament',
 'ultimate fighter china welterweight tournament',
 'ultimate fighter latin america 2 lightweight tournament',
 'ultimate fighter latin america 2 welterweight tournament',
 'ultimate fighter latin america 3 lightweight tournament',
 'ultimate fighter latin america bantamweight tournament',
 'ultimate fighter latin america featherweight tournament',
 'ultimate japan 2 heavyweight tournament',
 'ultimate japan heavyweight tournament',
 "ultimate ultimate '95 tournament",
 "ultimate ultimate '96 tournament",
 'welterweight',
 "women's bantamweight",
 "women's featherweight",
 "women's flyweight",
 "women's strawweight"]

In [20]:
df = ml_df.copy()

df["division"] = df["division"].str.lower()

# Remove interim prefix
df["division"] = df["division"].str.replace("interim ", "", regex=False)

valid_divisions = [
    "flyweight",
    "bantamweight",
    "featherweight",
    "lightweight",
    "welterweight",
    "middleweight",
    "light heavyweight",
    "heavyweight",
    "women's strawweight",
    "women's flyweight",
    "women's bantamweight",
    "women's featherweight"
]

df = df[df["division"].isin(valid_divisions)].copy()

print(df.shape)
print(df["division"].value_counts())

(7930, 29)
division
lightweight              1369
welterweight             1325
middleweight             1069
featherweight             795
heavyweight               719
bantamweight              712
light heavyweight         708
flyweight                 379
women's strawweight       343
women's flyweight         257
women's bantamweight      225
women's featherweight      29
Name: count, dtype: int64

In [21]:
df.isna().sum().sort_values(ascending=False).head(20)

b_reach         751
r_reach         296
b_height         10
b_weight          8
r_height          4
r_weight          2
b_str_def         0
b_splm            0
b_str_acc         0
b_sapm            0
r_wins            0
b_td_avg          0
b_td_avg_acc      0
b_sub_avg         0
division          0
title_fight       0
b_td_def          0
b_losses          0
r_losses          0
b_wins            0
dtype: int64

In [22]:
# Fill numeric missing values

for col in [
    "r_reach", "b_reach",
    "r_height", "b_height",
    "r_weight", "b_weight"
]:
    df[col] = df[col].fillna(df[col].median())

df.isna().sum().sort_values(ascending=False).head(10)

r_wins          0
b_height        0
title_fight     0
division        0
b_sub_avg       0
b_td_def        0
b_td_avg_acc    0
b_td_avg        0
b_str_def       0
b_sapm          0
dtype: int64

In [23]:
df = pd.get_dummies(
    df,
    columns=["division"],
    drop_first=True
)

df.shape

(7930, 39)

In [24]:
X = df.drop(columns=["target"])
y = df["target"]

print(X.shape)
print(y.shape)

(7930, 38)
(7930,)

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(6344, 38)
(1586, 38)

In [26]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=300, n_jobs=-1, random_state=42)

In [27]:
from sklearn.metrics import accuracy_score

preds = rf.predict(X_test)

accuracy = accuracy_score(y_test, preds)

print("Accuracy:", accuracy)

Accuracy: 0.7200504413619168

In [28]:
importance = pd.DataFrame({
    "feature": X.columns,
    "importance": rf.feature_importances_
})

importance.sort_values(
    "importance",
    ascending=False
).head(20)

         feature  importance
18        b_splm    0.068963
7         r_sapm    0.053058
0         r_wins    0.051719
24      b_td_def    0.051155
13        b_wins    0.044879
5         r_splm    0.044392
14      b_losses    0.044156
20        b_sapm    0.043886
19     b_str_acc    0.043315
22      b_td_avg    0.039899
6      r_str_acc    0.039149
11      r_td_def    0.038454
9       r_td_avg    0.038275
10  r_td_avg_acc    0.037969
23  b_td_avg_acc    0.037837
21     b_str_def    0.035803
8      r_str_def    0.035457
1       r_losses    0.034932
12     r_sub_avg    0.028555
17       b_reach    0.027765

In [31]:
# Create matchup-difference features

df_v2 = df.copy()

df_v2["wins_diff"] = df_v2["r_wins"] - df_v2["b_wins"]
df_v2["losses_diff"] = df_v2["r_losses"] - df_v2["b_losses"]

df_v2["height_diff"] = df_v2["r_height"] - df_v2["b_height"]
df_v2["weight_diff"] = df_v2["r_weight"] - df_v2["b_weight"]
df_v2["reach_diff"] = df_v2["r_reach"] - df_v2["b_reach"]

df_v2["splm_diff"] = df_v2["r_splm"] - df_v2["b_splm"]
df_v2["str_acc_diff"] = df_v2["r_str_acc"] - df_v2["b_str_acc"]
df_v2["sapm_diff"] = df_v2["r_sapm"] - df_v2["b_sapm"]
df_v2["str_def_diff"] = df_v2["r_str_def"] - df_v2["b_str_def"]

df_v2["td_avg_diff"] = df_v2["r_td_avg"] - df_v2["b_td_avg"]
df_v2["td_acc_diff"] = df_v2["r_td_avg_acc"] - df_v2["b_td_avg_acc"]
df_v2["td_def_diff"] = df_v2["r_td_def"] - df_v2["b_td_def"]

df_v2["sub_avg_diff"] = df_v2["r_sub_avg"] - df_v2["b_sub_avg"]

In [30]:
diff_features = [
    "wins_diff",
    "losses_diff",
    "height_diff",
    "weight_diff",
    "reach_diff",
    "splm_diff",
    "str_acc_diff",
    "sapm_diff",
    "str_def_diff",
    "td_avg_diff",
    "td_acc_diff",
    "td_def_diff",
    "sub_avg_diff",
    "title_fight"
]

division_columns = [
    col for col in df_v2.columns
    if col.startswith("division_")
]

X_v2 = df_v2[diff_features + division_columns]
y_v2 = df_v2["target"]

print(X_v2.shape)

(7930, 25)

In [32]:
X_train_v2, X_test_v2, y_train_v2, y_test_v2 = train_test_split(
    X_v2,
    y_v2,
    test_size=0.2,
    random_state=42,
    stratify=y_v2
)

rf_v2 = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf_v2.fit(X_train_v2, y_train_v2)

preds_v2 = rf_v2.predict(X_test_v2)

accuracy_v2 = accuracy_score(y_test_v2, preds_v2)

print("Model V1 Accuracy:", accuracy)
print("Model V2 Accuracy:", accuracy_v2)

Model V1 Accuracy: 0.7200504413619168
Model V2 Accuracy: 0.7049180327868853

In [33]:
from sklearn.metrics import classification_report

print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.66      0.44      0.53       569
           1       0.74      0.88      0.80      1017

    accuracy                           0.72      1586
   macro avg       0.70      0.66      0.67      1586
weighted avg       0.71      0.72      0.70      1586

In [34]:
mirror_df = df.copy()

# Swap red and blue fighter stats

swap_pairs = [
    ("r_wins", "b_wins"),
    ("r_losses", "b_losses"),
    ("r_height", "b_height"),
    ("r_weight", "b_weight"),
    ("r_reach", "b_reach"),
    ("r_splm", "b_splm"),
    ("r_str_acc", "b_str_acc"),
    ("r_sapm", "b_sapm"),
    ("r_str_def", "b_str_def"),
    ("r_td_avg", "b_td_avg"),
    ("r_td_avg_acc", "b_td_avg_acc"),
    ("r_td_def", "b_td_def"),
    ("r_sub_avg", "b_sub_avg")
]

for r_col, b_col in swap_pairs:
    mirror_df[r_col] = df[b_col]
    mirror_df[b_col] = df[r_col]

# Reverse target
mirror_df["target"] = 1 - df["target"]

In [35]:
balanced_df = pd.concat(
    [df, mirror_df],
    ignore_index=True
)

print(balanced_df.shape)

print(
    balanced_df["target"]
    .value_counts(normalize=True)
)

(15860, 39)
target
1    0.5
0    0.5
Name: proportion, dtype: float64

In [36]:
X_balanced = balanced_df.drop(columns=["target"])
y_balanced = balanced_df["target"]

print(X_balanced.shape)
print(y_balanced.shape)

(15860, 38)
(15860,)

In [37]:
from sklearn.model_selection import train_test_split

X_train_b, X_test_b, y_train_b, y_test_b = train_test_split(
    X_balanced,
    y_balanced,
    test_size=0.2,
    random_state=42,
    stratify=y_balanced
)

print(X_train_b.shape)
print(X_test_b.shape)

(12688, 38)
(3172, 38)

In [38]:
from sklearn.ensemble import RandomForestClassifier

rf_balanced_data = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf_balanced_data.fit(X_train_b, y_train_b)

preds_b = rf_balanced_data.predict(X_test_b)

In [39]:
from sklearn.metrics import accuracy_score, classification_report

print("Balanced Dataset Accuracy:",
      accuracy_score(y_test_b, preds_b))

print(classification_report(y_test_b, preds_b))

Balanced Dataset Accuracy: 0.7042875157629256
              precision    recall  f1-score   support

           0       0.70      0.71      0.71      1586
           1       0.71      0.69      0.70      1586

    accuracy                           0.70      3172
   macro avg       0.70      0.70      0.70      3172
weighted avg       0.70      0.70      0.70      3172

In [40]:
from sklearn.model_selection import train_test_split

# Split original fights first
train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df["target"]
)

print(train_df.shape)
print(test_df.shape)

(6344, 39)
(1586, 39)

In [41]:
def mirror_fights(source_df):
    mirrored = source_df.copy()

    swap_pairs = [
        ("r_wins", "b_wins"),
        ("r_losses", "b_losses"),
        ("r_height", "b_height"),
        ("r_weight", "b_weight"),
        ("r_reach", "b_reach"),
        ("r_splm", "b_splm"),
        ("r_str_acc", "b_str_acc"),
        ("r_sapm", "b_sapm"),
        ("r_str_def", "b_str_def"),
        ("r_td_avg", "b_td_avg"),
        ("r_td_avg_acc", "b_td_avg_acc"),
        ("r_td_def", "b_td_def"),
        ("r_sub_avg", "b_sub_avg")
    ]

    for r_col, b_col in swap_pairs:
        mirrored[r_col] = source_df[b_col].values
        mirrored[b_col] = source_df[r_col].values

    mirrored["target"] = 1 - source_df["target"].values

    return pd.concat(
        [source_df, mirrored],
        ignore_index=True
    )

In [42]:
train_balanced = mirror_fights(train_df)
test_balanced = mirror_fights(test_df)

print(train_balanced.shape)
print(test_balanced.shape)

print(train_balanced["target"].value_counts(normalize=True))
print(test_balanced["target"].value_counts(normalize=True))

(12688, 39)
(3172, 39)
target
1    0.5
0    0.5
Name: proportion, dtype: float64
target
1    0.5
0    0.5
Name: proportion, dtype: float64

In [43]:
X_train_final = train_balanced.drop(columns=["target"])
y_train_final = train_balanced["target"]

X_test_final = test_balanced.drop(columns=["target"])
y_test_final = test_balanced["target"]

rf_final = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf_final.fit(X_train_final, y_train_final)

preds_final = rf_final.predict(X_test_final)

print(
    "Leakage-safe accuracy:",
    accuracy_score(y_test_final, preds_final)
)

print(classification_report(y_test_final, preds_final))

Leakage-safe accuracy: 0.7036569987389659
              precision    recall  f1-score   support

           0       0.70      0.71      0.70      1586
           1       0.71      0.70      0.70      1586

    accuracy                           0.70      3172
   macro avg       0.70      0.70      0.70      3172
weighted avg       0.70      0.70      0.70      3172

In [45]:
import os
print(os.getcwd())

/Users/apple/Desktop/kombat-ai/notebooks

In [46]:
import os

print(os.path.exists("../models"))

True

In [47]:
import joblib

joblib.dump(rf_final, "../models/kombat_ai_rf.pkl")

['../models/kombat_ai_rf.pkl']

In [48]:
import os

os.listdir("../models")

['kombat_ai_rf.pkl']